server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:  Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE
                fallbackuri: forward:/userServiceFallBack
        - id: BUG-SERVICE
          uri: lb://BUG-SERVICE
          predicates:
            - Path=/bugs/**,/bug/**,/comments/**,/comment/**
          filters:
            - name: CircuitBreaker
              args:
                name: BUG-SERVICE
                fallbackuri: forward:/bugServiceFallBack
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates: Path=/products/**
          filters:
            - name: CircuitBreaker
              args:
                name: PRODUCT-SERVICE
                fallbackuri: forward:/productServiceFallBack

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka