global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'product_service'
    metrics_path: 'actuator/prometheus'
    static_configs:
      - targets: ['product-service:9004']
        labels:
          application: 'Product Service Application'
  - job_name: 'user_service'
    metrics_path: 'actuator/prometheus'
    static_configs:
      - targets: ['user-service:9002']
        labels:
          application: 'User Service Application'
  - job_name: 'bug_service'
    metrics_path: 'actuator/prometheus'
    static_configs:
      - targets: ['bug-service:9003']
        labels:
          application: 'Bug Service Application'