Server:
  Port: 9002

spring:
  datasource:
    url: jdbc:h2:mem:test
    username: root
    password: root
    driverClassName: org.h2.Driver
  application:
    name: USER-SERVICE
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
    ddl-auto: update
  h2:
    console.enabled: true
  zipkin:
    base-url: http://localhost:9411/
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"