Server:
  Port: 9002

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka
