FROM eclipse-temurin:11 as builder
WORKDIR extracted
ADD target/*.jar hystrix-dashboard.jar
RUN java -Djarmode=layertools -jar hystrix-dashboard.jar extract

FROM eclipse-temurin:11
WORKDIR application
COPY --from=builder extracted/dependencies/ ./
COPY --from=builder extracted/spring-boot-loader/ ./
COPY --from=builder extracted/snapshot-dependencies/ ./
COPY --from=builder extracted/application/ ./
ENTRYPOINT ["java", "org.springframework.boot.loader.JarLauncher"]