Server:
  Port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

spring:
  zipkin:
    base-url: http://zipkin:9411/

management:
  endpoints:
    web:
      exposure:
        include: "*"